# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Checklist.Api

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Checklist.Api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Checklist.Api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Checklist.Api/Checklist.Api.sln
    - name: Build
      run: dotnet build src/Checklist.Api/Checklist.Api.sln --no-restore
    - name: Test
      run: dotnet test src/Checklist.Api/Checklist.Api.sln --no-build --verbosity normal
